blank_issues_enabled: false
contact_links:
    - name: Support & Feedback
      url: https://github.com/archetyped/cornerstone/wiki/Support-&-Feedback
      about: How to get support and share feedback for Cornerstone